### ISSUE TITLE
Window changes it's size when new file is opened

### ISSUE THREAD

**Issue by tishun** [nickbnf/glogg#148]
Hey there, love the app! There is only one issue that really bugs - when I maximize the glogg window and then proceed to open a new file (not via the File -> open, but instead double click on a log file in windows file explorer) the window changes its position and size.

I saw that there is a similar issue #130 already logged, although it deals only with the initial start of the program. I have tried checking "Load last session" in Tools->Options with no change.

Using glogg v.1.1.2-x86_64 on Windows 10 Enterprise / Version 1607 / OS build 14393.693

**Comment by nickbnf** [comment]
Interesting, I just tried on Win7 and it all works fine, I wonder if it's a specific problem to W10. Anybody else has seen the problem?

**Comment by tishun** [comment]
I seem to recall that I had the same issue with Win7, but I am not entirely sure.

**Comment by rob3rtb** [comment]
Hi, I get exactly the same problem on Windows 10 glogg version 1.1.2-x86_64

**Comment by nickbnf** [comment]
I've fixed #130 in d1edc4fc7754897c93766534d94609fa554a8f80 and also changed the code slightly to size the window before drawing it, as recommended by the Qt doc. It might solve the problem. Everything is fine on Linux/Mac/W7 and I can't test on W10 so do let me know.

**Comment by tishun** [comment]
Is this part of some update that I can try out?

**Comment by nickbnf** [comment]
It is in the latest v1.1.3.

**Comment by tishun** [comment]
Unfortunately still having the same issue with v1.1.3-x86_64

Although, to be fair, when the window is initially loaded it applies the last size / position.
However when I maximize it, and then double click on a file in the file explorer, it reverts to the same position the application was started in.

E.g. steps:
1. Open the app, resize and move the window to the bottom, double click - no issues, window remains the same.
2. Close the app and open it again - no issue again, window is positioned in the same place.

However the moment I maximize and then double click to open another file it is reverted to the last position from step 1.

**Comment by Eraser3** [comment]
I'm having the same problems on Windows 7 professional with Glogg version 1.1.4.
When opening a file from Windows Explorer the Glogg window resizes from maximized to whatever state it was before that.
